version: '3.3'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5433:5432'
    volumes: 
      - ../db:/var/lib/postgresql/data
    container_name: postgres_craft
volumes:
  database:
    driver: local